import React, { useState, useEffect } from 'react';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogFooter,
} from '../ui/dialog';
import { Button } from '../ui/button';
import { Input } from '../ui/input';
import { Label } from '../ui/label';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '../ui/select';
import { Check } from 'lucide-react';
import { Project, WorkType, ProjectStatus } from '../../types';
import { WORK_TYPES } from '../../lib/workTypes';
import { WORK_TYPE_STYLES } from '../project/WorkTypeTags';
import { cn } from '../../lib/utils';

interface ProjectDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  onSave: (project: Omit<Project, 'id'>) => void;
  editProject?: Project | null;
  clients: Array<{ id: string; companyName: string }>;
  cities: string[];
  onAddCity: (city: string) => void;
}

interface FormState {
  name: string;
  address: string;
  city: string;
  clientId: string;
  workTypes: WorkType[];
  status: ProjectStatus;
}

const EMPTY_FORM: FormState = {
  name: '',
  address: '',
  city: '',
  clientId: '',
  workTypes: ['Blueprints'],
  status: 'Active',
};

const ProjectDialog: React.FC<ProjectDialogProps> = ({
  open,
  onOpenChange,
  onSave,
  editProject,
  clients,
  cities,
  onAddCity,
}) => {
  const [formData, setFormData] = useState<FormState>(EMPTY_FORM);
  const [touchedTags, setTouchedTags] = useState(false);

  useEffect(() => {
    if (editProject) {
      setFormData({
        name: editProject.name,
        address: editProject.address,
        city: editProject.city || '',
        clientId: editProject.clientId,
        workTypes: editProject.workTypes ?? [],
        status: editProject.status,
      });
    } else {
      setFormData(EMPTY_FORM);
    }
    setTouchedTags(false);
  }, [editProject, open]);

  const toggleWorkType = (type: WorkType) => {
    setTouchedTags(true);
    setFormData((prev) => {
      const has = prev.workTypes.includes(type);
      const next = has ? prev.workTypes.filter((t) => t !== type) : [...prev.workTypes, type];
      // Keep a stable display order.
      return { ...prev, workTypes: WORK_TYPES.filter((t) => next.includes(t)) };
    });
  };

  const noTags = formData.workTypes.length === 0;

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (noTags) {
      setTouchedTags(true);
      return;
    }
    if (formData.name && formData.clientId) {
      // Add placeholder color (will be generated by context for new projects)
      onSave({
        ...formData,
        color: editProject?.color || '',
      });
      onOpenChange(false);
    }
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-[425px]">
        <DialogHeader>
          <DialogTitle>
            {editProject ? 'Edit Project' : 'Add New Project'}
          </DialogTitle>
        </DialogHeader>
        <form onSubmit={handleSubmit}>
          <div className="grid gap-4 py-4">
            <div className="grid gap-2">
              <Label htmlFor="name">Project Name</Label>
              <Input
                id="name"
                value={formData.name}
                onChange={(e) =>
                  setFormData({ ...formData, name: e.target.value })
                }
                required
              />
            </div>
            <div className="grid gap-2">
              <Label htmlFor="address">Address</Label>
              <Input
                id="address"
                value={formData.address}
                onChange={(e) =>
                  setFormData({ ...formData, address: e.target.value })
                }
              />
            </div>
            <div className="grid gap-2">
              <Label htmlFor="city">City</Label>
              <Input
                id="city"
                list="cities-list"
                value={formData.city}
                onChange={(e) => {
                  setFormData({ ...formData, city: e.target.value });
                }}
                onBlur={() => {
                  if (formData.city && !cities.includes(formData.city)) {
                    onAddCity(formData.city);
                  }
                }}
              />
              <datalist id="cities-list">
                {cities.map((city) => (
                  <option key={city} value={city} />
                ))}
              </datalist>
            </div>
            <div className="grid gap-2">
              <Label htmlFor="client">Client</Label>
              <Select
                value={formData.clientId}
                onValueChange={(value) =>
                  setFormData({ ...formData, clientId: value })
                }
                required
              >
                <SelectTrigger>
                  <SelectValue placeholder="Select client" />
                </SelectTrigger>
                <SelectContent>
                  {clients.map((client) => (
                    <SelectItem key={client.id} value={client.id}>
                      {client.companyName}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
            <div className="grid gap-2">
              <div className="flex items-baseline justify-between">
                <Label>Work Types</Label>
                <span className="text-xs text-muted-foreground">Pick one or more</span>
              </div>
              <div className="flex flex-wrap gap-2" role="group" aria-label="Work types">
                {WORK_TYPES.map((type) => {
                  const active = formData.workTypes.includes(type);
                  return (
                    <button
                      key={type}
                      type="button"
                      role="checkbox"
                      aria-checked={active}
                      onClick={() => toggleWorkType(type)}
                      className={cn(
                        'inline-flex items-center gap-1 rounded-full border px-3 py-1 text-xs font-medium transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring',
                        active
                          ? cn('border-transparent', WORK_TYPE_STYLES[type])
                          : 'border-border/70 bg-transparent text-muted-foreground hover:bg-accent hover:text-foreground'
                      )}
                    >
                      {active && <Check className="h-3 w-3" aria-hidden="true" />}
                      {type}
                    </button>
                  );
                })}
              </div>
              {noTags && touchedTags && (
                <p className="text-xs font-medium text-destructive">Select at least one work type.</p>
              )}
            </div>
            <div className="grid gap-2">
              <Label htmlFor="status">Status</Label>
              <Select
                value={formData.status}
                onValueChange={(value: ProjectStatus) =>
                  setFormData({ ...formData, status: value })
                }
              >
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="Active">Active</SelectItem>
                  <SelectItem value="Paused">Paused</SelectItem>
                  <SelectItem value="Completed">Completed</SelectItem>
                </SelectContent>
              </Select>
            </div>
          </div>
          <DialogFooter>
            <Button type="button" variant="outline" onClick={() => onOpenChange(false)}>
              Cancel
            </Button>
            <Button type="submit">Save</Button>
          </DialogFooter>
        </form>
      </DialogContent>
    </Dialog>
  );
};

export default ProjectDialog;
